const INITIALIZE_NOTE_FORM = 'note/INITIALIZE_NOTE_FORM' as const;
const INITIALIZE_NOTE_INFO = 'note/INITIALIZE_NOTE_INFO' as const;

const CHANGE_INVESTMENT_DATE = 'note/CHANGE_INVESTMENT_DATE' as const;
const CHANGE_TEXT = 'note/CHANGE_TEXT' as const;
const CHANGE_ERROR = 'note/CHANGE_ERROR' as const;

const WRITE_NOTE = 'note/WRITE_NOTE' as const;
const WRITE_NOTE_SUCCESS = 'note/WRITE_NOTE_SUCCESS' as const;
const WRITE_NOTE_FAIL = 'note/WRITE_NOTE_FAIL' as const;

export {
  INITIALIZE_NOTE_FORM,
  INITIALIZE_NOTE_INFO,
  CHANGE_INVESTMENT_DATE,
  CHANGE_TEXT,
  CHANGE_ERROR,
  WRITE_NOTE,
  WRITE_NOTE_SUCCESS,
  WRITE_NOTE_FAIL,
};
